del /f /q dependencies\OgreBullet\Collisions\src\OgreBulletCollisionsObject.o
del /f /q dependencies\OgreBullet\Collisions\src\OgreBulletCollisionsObjectState.o
del /f /q dependencies\OgreBullet\Collisions\src\OgreBulletCollisionsPrecompiled.o
del /f /q dependencies\OgreBullet\Collisions\src\OgreBulletCollisionsRay.o
del /f /q dependencies\OgreBullet\Collisions\src\OgreBulletCollisionsShape.o
del /f /q dependencies\OgreBullet\Collisions\src\OgreBulletCollisionsWorld.o
del /f /q dependencies\OgreBullet\Collisions\src\Debug\OgreBulletCollisionsDebugContact.o
del /f /q dependencies\OgreBullet\Collisions\src\Debug\OgreBulletCollisionsDebugDrawer.o
del /f /q dependencies\OgreBullet\Collisions\src\Debug\OgreBulletCollisionsDebugLines.o
del /f /q dependencies\OgreBullet\Collisions\src\Debug\OgreBulletCollisionsDebugShape.o
del /f /q dependencies\OgreBullet\Collisions\src\Shapes\OgreBulletCollisionsBoxShape.o
del /f /q dependencies\OgreBullet\Collisions\src\Shapes\OgreBulletCollisionsCapsuleShape.o
del /f /q dependencies\OgreBullet\Collisions\src\Shapes\OgreBulletCollisionsCompoundShape.o
del /f /q dependencies\OgreBullet\Collisions\src\Shapes\OgreBulletCollisionsConeShape.o
del /f /q dependencies\OgreBullet\Collisions\src\Shapes\OgreBulletCollisionsConvexHullShape.o
del /f /q dependencies\OgreBullet\Collisions\src\Shapes\OgreBulletCollisionsCylinderShape.o
del /f /q dependencies\OgreBullet\Collisions\src\Shapes\OgreBulletCollisionsGImpactShape.o
del /f /q dependencies\OgreBullet\Collisions\src\Shapes\OgreBulletCollisionsMinkowskiSumShape.o
del /f /q dependencies\OgreBullet\Collisions\src\Shapes\OgreBulletCollisionsMultiSphereShape.o
del /f /q dependencies\OgreBullet\Collisions\src\Shapes\OgreBulletCollisionsSphereShape.o
del /f /q dependencies\OgreBullet\Collisions\src\Shapes\OgreBulletCollisionsStaticPlaneShape.o
del /f /q dependencies\OgreBullet\Collisions\src\Shapes\OgreBulletCollisionsTriangleShape.o
del /f /q dependencies\OgreBullet\Collisions\src\Shapes\OgreBulletCollisionsTrimeshShape.o
del /f /q dependencies\OgreBullet\Dynamics\src\OgreBulletDynamicsConstraint.o
del /f /q dependencies\OgreBullet\Dynamics\src\OgreBulletDynamicsObjectState.o
del /f /q dependencies\OgreBullet\Dynamics\src\OgreBulletDynamicsPrecompiled.o
del /f /q dependencies\OgreBullet\Dynamics\src\OgreBulletDynamicsRigidBody.o
del /f /q dependencies\OgreBullet\Dynamics\src\OgreBulletDynamicsWorld.o
del /f /q dependencies\OgreBullet\Dynamics\src\Prefab\OgreBulletDynamicsRagDoll.o
del /f /q dependencies\OgreBullet\Dynamics\src\Constraints\OgreBulletDynamics6DofConstraint.o
del /f /q dependencies\OgreBullet\Dynamics\src\Constraints\OgreBulletDynamics6DofSpringConstraint.o
del /f /q dependencies\OgreBullet\Dynamics\src\Constraints\OgreBulletDynamicsConeTwistConstraint.o
del /f /q dependencies\OgreBullet\Dynamics\src\Constraints\OgreBulletDynamicsHingeConstraint.o
del /f /q dependencies\OgreBullet\Dynamics\src\Constraints\OgreBulletDynamicsPoint2pointConstraint.o
del /f /q dependencies\OgreBullet\Dynamics\src\Constraints\OgreBulletDynamicsRaycastVehicle.o
del /f /q dependencies\luabind\src\class.o
del /f /q dependencies\luabind\src\class_info.o
del /f /q dependencies\luabind\src\class_registry.o
del /f /q dependencies\luabind\src\class_rep.o
del /f /q dependencies\luabind\src\create_class.o
del /f /q dependencies\luabind\src\error.o
del /f /q dependencies\luabind\src\exception_handler.o
del /f /q dependencies\luabind\src\function.o
del /f /q dependencies\luabind\src\inheritance.o
del /f /q dependencies\luabind\src\link_compatibility.o
del /f /q dependencies\luabind\src\object_rep.o
del /f /q dependencies\luabind\src\open.o
del /f /q dependencies\luabind\src\pcall.o
del /f /q dependencies\luabind\src\scope.o
del /f /q dependencies\luabind\src\stack_content_by_name.o
del /f /q dependencies\luabind\src\weak_ref.o
del /f /q dependencies\luabind\src\wrapper_base.o
del /f /q src\main.o
del /f /q src\actors\BouncePowerUp.o
del /f /q src\actors\CollectibleMarble.o
del /f /q src\actors\CompetitorMarble.o
del /f /q src\actors\FloatPowerUp.o
del /f /q src\actors\HealthPowerUp.o
del /f /q src\actors\HelpPowerUp.o
del /f /q src\actors\SpeedPowerUp.o
del /f /q src\actors\StickyPowerUp.o
del /f /q src\actors\TeleportPowerUp.o
del /f /q src\behaviors\LostBehavior.o
del /f /q src\behaviors\PlayerBehavior.o
del /f /q src\behaviors\RivalBehavior.o
del /f /q src\helpers\OverlayFader.o
del /f /q src\managers\DotLevelLoader.o
del /f /q src\managers\GameManager.o
del /f /q src\managers\InputManager.o
del /f /q src\managers\LuaBinding.o
del /f /q src\managers\SoundManager.o
del /f /q src\managers\TextRenderer.o
del /f /q src\powerups\BouncePowerUpBehavior.o
del /f /q src\powerups\FloatPowerUpBehavior.o
del /f /q src\powerups\SpeedPowerUpBehavior.o
del /f /q src\powerups\StickyPowerUpBehavior.o
del /f /q src\powerups\UnderwaterBehavior.o
del /f /q src\states\BlankState.o
del /f /q src\states\LogoState.o
del /f /q src\states\MainMenuState.o
del /f /q src\states\PauseState.o
del /f /q src\states\PlayState.o
del /f /q src\states\QuitGameState.o
del /f /q src\states\WinState.o