del /f /q dependencies\Bullet\BulletCollision\CollisionDispatch\btSimulationIslandManager.o
del /f /q dependencies\Bullet\ConvexDecomposition\bestfit.o
del /f /q dependencies\Bullet\ConvexDecomposition\bestfitobb.o
del /f /q dependencies\Bullet\ConvexDecomposition\cd_hull.o
del /f /q dependencies\Bullet\ConvexDecomposition\cd_wavefront.o
del /f /q dependencies\Bullet\ConvexDecomposition\concavity.o
del /f /q dependencies\Bullet\ConvexDecomposition\ConvexBuilder.o
del /f /q dependencies\Bullet\ConvexDecomposition\ConvexDecomposition.o
del /f /q dependencies\Bullet\ConvexDecomposition\fitsphere.o
del /f /q dependencies\Bullet\ConvexDecomposition\float_math.o
del /f /q dependencies\Bullet\ConvexDecomposition\meshvolume.o
del /f /q dependencies\Bullet\ConvexDecomposition\planetri.o
del /f /q dependencies\Bullet\ConvexDecomposition\raytri.o
del /f /q dependencies\Bullet\ConvexDecomposition\splitplane.o
del /f /q dependencies\Bullet\ConvexDecomposition\vlookup.o
del /f /q dependencies\OgreBullet\Collisions\src\OgreBulletCollisionsObject.o
del /f /q dependencies\OgreBullet\Collisions\src\OgreBulletCollisionsObjectState.o
del /f /q dependencies\OgreBullet\Collisions\src\OgreBulletCollisionsPrecompiled.o
del /f /q dependencies\OgreBullet\Collisions\src\OgreBulletCollisionsRay.o
del /f /q dependencies\OgreBullet\Collisions\src\OgreBulletCollisionsShape.o
del /f /q dependencies\OgreBullet\Collisions\src\OgreBulletCollisionsWorld.o
del /f /q dependencies\OgreBullet\Collisions\src\Debug\OgreBulletCollisionsDebugContact.o
del /f /q dependencies\OgreBullet\Collisions\src\Debug\OgreBulletCollisionsDebugDrawer.o
del /f /q dependencies\OgreBullet\Collisions\src\Debug\OgreBulletCollisionsDebugLines.o
del /f /q dependencies\OgreBullet\Collisions\src\Debug\OgreBulletCollisionsDebugShape.o
del /f /q dependencies\OgreBullet\Collisions\src\Shapes\OgreBulletCollisionsBoxShape.o
del /f /q dependencies\OgreBullet\Collisions\src\Shapes\OgreBulletCollisionsCapsuleShape.o
del /f /q dependencies\OgreBullet\Collisions\src\Shapes\OgreBulletCollisionsCompoundShape.o
del /f /q dependencies\OgreBullet\Collisions\src\Shapes\OgreBulletCollisionsConeShape.o
del /f /q dependencies\OgreBullet\Collisions\src\Shapes\OgreBulletCollisionsConvexHullShape.o
del /f /q dependencies\OgreBullet\Collisions\src\Shapes\OgreBulletCollisionsCylinderShape.o
del /f /q dependencies\OgreBullet\Collisions\src\Shapes\OgreBulletCollisionsGImpactShape.o
del /f /q dependencies\OgreBullet\Collisions\src\Shapes\OgreBulletCollisionsMinkowskiSumShape.o
del /f /q dependencies\OgreBullet\Collisions\src\Shapes\OgreBulletCollisionsMultiSphereShape.o
del /f /q dependencies\OgreBullet\Collisions\src\Shapes\OgreBulletCollisionsSphereShape.o
del /f /q dependencies\OgreBullet\Collisions\src\Shapes\OgreBulletCollisionsStaticPlaneShape.o
del /f /q dependencies\OgreBullet\Collisions\src\Shapes\OgreBulletCollisionsTriangleShape.o
del /f /q dependencies\OgreBullet\Collisions\src\Shapes\OgreBulletCollisionsTrimeshShape.o
del /f /q dependencies\OgreBullet\Collisions\src\Utils\OgreBulletCollisionsMeshToShapeConverter.o
del /f /q dependencies\OgreBullet\Dynamics\src\OgreBulletDynamicsConstraint.o
del /f /q dependencies\OgreBullet\Dynamics\src\OgreBulletDynamicsObjectState.o
del /f /q dependencies\OgreBullet\Dynamics\src\OgreBulletDynamicsPrecompiled.o
del /f /q dependencies\OgreBullet\Dynamics\src\OgreBulletDynamicsRigidBody.o
del /f /q dependencies\OgreBullet\Dynamics\src\OgreBulletDynamicsWorld.o
del /f /q dependencies\OgreBullet\Dynamics\src\Prefab\OgreBulletDynamicsRagDoll.o
del /f /q dependencies\OgreBullet\Dynamics\src\Constraints\OgreBulletDynamics6DofConstraint.o
del /f /q dependencies\OgreBullet\Dynamics\src\Constraints\OgreBulletDynamics6DofSpringConstraint.o
del /f /q dependencies\OgreBullet\Dynamics\src\Constraints\OgreBulletDynamicsConeTwistConstraint.o
del /f /q dependencies\OgreBullet\Dynamics\src\Constraints\OgreBulletDynamicsHingeConstraint.o
del /f /q dependencies\OgreBullet\Dynamics\src\Constraints\OgreBulletDynamicsPoint2pointConstraint.o
del /f /q dependencies\OgreBullet\Dynamics\src\Constraints\OgreBulletDynamicsRaycastVehicle.o
del /f /q dependencies\luabind\src\class.o
del /f /q dependencies\luabind\src\class_info.o
del /f /q dependencies\luabind\src\class_registry.o
del /f /q dependencies\luabind\src\class_rep.o
del /f /q dependencies\luabind\src\create_class.o
del /f /q dependencies\luabind\src\error.o
del /f /q dependencies\luabind\src\exception_handler.o
del /f /q dependencies\luabind\src\function.o
del /f /q dependencies\luabind\src\inheritance.o
del /f /q dependencies\luabind\src\link_compatibility.o
del /f /q dependencies\luabind\src\object_rep.o
del /f /q dependencies\luabind\src\open.o
del /f /q dependencies\luabind\src\pcall.o
del /f /q dependencies\luabind\src\scope.o
del /f /q dependencies\luabind\src\stack_content_by_name.o
del /f /q dependencies\luabind\src\weak_ref.o
del /f /q dependencies\luabind\src\wrapper_base.o
del /f /q dependencies\lua\src\lapi.o
del /f /q dependencies\lua\src\lauxlib.o
del /f /q dependencies\lua\src\lbaselib.o
del /f /q dependencies\lua\src\lcode.o
del /f /q dependencies\lua\src\ldblib.o
del /f /q dependencies\lua\src\ldebug.o
del /f /q dependencies\lua\src\ldo.o
del /f /q dependencies\lua\src\ldump.o
del /f /q dependencies\lua\src\lfunc.o
del /f /q dependencies\lua\src\lgc.o
del /f /q dependencies\lua\src\linit.o
del /f /q dependencies\lua\src\liolib.o
del /f /q dependencies\lua\src\llex.o
del /f /q dependencies\lua\src\lmathlib.o
del /f /q dependencies\lua\src\lmem.o
del /f /q dependencies\lua\src\loadlib.o
del /f /q dependencies\lua\src\lobject.o
del /f /q dependencies\lua\src\lopcodes.o
del /f /q dependencies\lua\src\loslib.o
del /f /q dependencies\lua\src\lparser.o
del /f /q dependencies\lua\src\lstate.o
del /f /q dependencies\lua\src\lstring.o
del /f /q dependencies\lua\src\lstrlib.o
del /f /q dependencies\lua\src\ltable.o
del /f /q dependencies\lua\src\ltablib.o
del /f /q dependencies\lua\src\ltm.o
del /f /q dependencies\lua\src\lundump.o
del /f /q dependencies\lua\src\lvm.o
del /f /q dependencies\lua\src\lzio.o
del /f /q dependencies\lua\src\print.o
del /f /q dependencies\freetype\src\base\ftsystem.o
del /f /q dependencies\freetype\src\base\ftinit.o
del /f /q dependencies\freetype\src\base\ftdebug.o
del /f /q dependencies\freetype\src\base\ftbase.o
del /f /q dependencies\freetype\src\base\ftbbox.o
del /f /q dependencies\freetype\src\base\ftglyph.o
del /f /q dependencies\freetype\src\base\ftbdf.o
del /f /q dependencies\freetype\src\base\ftbitmap.o
del /f /q dependencies\freetype\src\base\ftcid.o
del /f /q dependencies\freetype\src\base\ftfstype.o
del /f /q dependencies\freetype\src\base\ftgasp.o
del /f /q dependencies\freetype\src\base\ftgxval.o
del /f /q dependencies\freetype\src\base\ftlcdfil.o
del /f /q dependencies\freetype\src\base\ftmm.o
del /f /q dependencies\freetype\src\base\ftotval.o
del /f /q dependencies\freetype\src\base\ftpatent.o
del /f /q dependencies\freetype\src\base\ftpfr.o
del /f /q dependencies\freetype\src\base\ftstroke.o
del /f /q dependencies\freetype\src\base\ftsynth.o
del /f /q dependencies\freetype\src\base\fttype1.o
del /f /q dependencies\freetype\src\base\ftwinfnt.o
del /f /q dependencies\freetype\src\base\ftxf86.o
del /f /q dependencies\freetype\src\truetype\truetype.o
del /f /q dependencies\freetype\src\smooth\smooth.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_Button.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_Canvas.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_ComboBox.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_DDContainer.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_Edit.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_HScroll.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_ItemBox.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_List.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_ListBox.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_ListCtrl.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_MenuBar.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_MenuCtrl.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_MenuItem.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_Message.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_MultiList.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_PopupMenu.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_Progress.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_ScrollView.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_StaticImage.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_StaticText.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_Tab.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_TabItem.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_VScroll.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_Widget.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_Window.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_EditText.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_MainSkin.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_RawRect.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_RotatingSkin.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_SimpleText.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_SubSkin.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_TileRect.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_LayerItem.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_LayerNode.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_OverlappedLayer.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_RenderItem.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_SharedLayer.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_SharedLayerNode.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_ActionController.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_ControllerEdgeHide.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_ControllerFadeAlpha.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_ControllerPosition.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_Exception.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_Precompiled.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_IWidgetCreator.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_ScrollViewBase.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_ResourceImageSet.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_ResourceImageSetPointer.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_ResourceManualFont.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_ResourceManualPointer.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_ResourceSkin.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_ResourceTrueTypeFont.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_MaskPickInfo.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_Any.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_Colour.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_ClipboardManager.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_ControllerManager.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_DataManager.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_DynLibManager.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_FactoryManager.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_FontManager.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_Gui.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_InputManager.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_LanguageManager.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_LayerManager.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_LayoutManager.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_PluginManager.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_PointerManager.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_RenderManager.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_ResourceManager.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_SkinManager.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_SubWidgetManager.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_WidgetManager.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_DataFileStream.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_DataStream.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_DynLib.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_Guid.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_RenderOut.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_TextIterator.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_TextureUtility.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_Timer.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_XmlDocument.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_LogManager.o
del /f /q dependencies\MyGUI\MyGUIEngine\src\MyGUI_LogStream.o
del /f /q dependencies\MyGUI\Platforms\Ogre\OgrePlatform\src\MyGUI_OgreDataManager.o
del /f /q dependencies\MyGUI\Platforms\Ogre\OgrePlatform\src\MyGUI_OgreDataStream.o
del /f /q dependencies\MyGUI\Platforms\Ogre\OgrePlatform\src\MyGUI_OgreRenderManager.o
del /f /q dependencies\MyGUI\Platforms\Ogre\OgrePlatform\src\MyGUI_OgreTexture.o
del /f /q dependencies\MyGUI\Platforms\Ogre\OgrePlatform\src\MyGUI_OgreRTTexture.o
del /f /q dependencies\MyGUI\Platforms\Ogre\OgrePlatform\src\MyGUI_OgreVertexBuffer.o
del /f /q src\main.o
del /f /q src\actors\BouncePowerUp.o
del /f /q src\actors\CollectibleMarble.o
del /f /q src\actors\CompetitorMarble.o
del /f /q src\actors\FloatPowerUp.o
del /f /q src\actors\HealthPowerUp.o
del /f /q src\actors\HelpPowerUp.o
del /f /q src\actors\SpeedPowerUp.o
del /f /q src\actors\StickyPowerUp.o
del /f /q src\actors\TeleportPowerUp.o
del /f /q src\behaviors\LostBehavior.o
del /f /q src\behaviors\PlayerBehavior.o
del /f /q src\behaviors\RivalBehavior.o
del /f /q src\helpers\OverlayFader.o
del /f /q src\managers\DotLevelLoader.o
del /f /q src\managers\GameManager.o
del /f /q src\managers\InputManager.o
del /f /q src\managers\LuaBinding.o
del /f /q src\managers\SoundManager.o
del /f /q src\managers\TextRenderer.o
del /f /q src\powerups\BouncePowerUpBehavior.o
del /f /q src\powerups\FloatPowerUpBehavior.o
del /f /q src\powerups\SpeedPowerUpBehavior.o
del /f /q src\powerups\StickyPowerUpBehavior.o
del /f /q src\powerups\UnderwaterBehavior.o
del /f /q src\states\BlankState.o
del /f /q src\states\LogoState.o
del /f /q src\states\MainMenuState.o
del /f /q src\states\PauseState.o
del /f /q src\states\PlayState.o
del /f /q src\states\QuitGameState.o
del /f /q src\states\WinState.o